### ISSUE TITLE
feat(jxl): consolidate environment repository system and apps directories 

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x-labs/issues#11]
### Summary 

`jx` installed apps are bootstrapped with the default values from the `jenkins-x-versions/apps/$chartName/values.yaml.gotmpl` templates. Values can be overwritten / charts can be customized in the `jxl` extension model by setting custom values for the chart in the `apps/$chartName/values.yaml` or `system/$chartName/values.yaml` values files.

The `system` charts are those installed during the `system` phase which creates the set of resources later used during the deployment phase of the `apps` - e.g. the installation of `cert-manager`, `nginx-ingress`, `external-dns` which are created / configured during the system phase to enable certificate issuance for the services created during the apps deployment.

**Problem**: the separation of `system` and `apps` directories can lead to unintended behavior if incorrectly configured for the `jx boot run`, example: the user creates a `values.yaml` customization for the `nginx-ingress` service in the `apps/nginx-ingress` directory expecting the values to be taken into account - they are not, the `helmfile` generated resources does not contain the correct `values`, the `nginx-ingress` service is created with defaults from the `jenkins-x-versions` templates which are incorrect which domino's (incorrect service is published, load balancer IP is never allocated, apps are deployed with incorrect ingress, ...).

**Proposal**: consolidate the `apps` and `system` directory resources in a single directory: `environment-cluster-tenant/apps` directory and handle the `system` / `apps` phase logic in the code (`for customization in customizations; if [ $customization in "nginx-ingress" "cert-manager" "external-dns" ]; do foobar; fi; done`). +1 for user experience and easier to (possibly) package and ship different flavors of `jxl`.

### Steps to reproduce the behavior

`jxl run boot` from an environments repository with `stable/nginx-ingress` configured in the `jx-apps.yml` and an attempt to customize the `nginx-ingress` service using a `environment-cluster-tenant/apps/nginx-ingress/values.yaml` file.

### Expected behavior

`stable/nginx-ingress` chart installed using the values set in the `environment-cluster-tenant/apps/nginx-ingress/values.yaml`.

### Actual behavior

`helmfile` is generated without custom values from `environment-cluster-tenant/apps/nginx-ingress/values.yaml`, chart is "incorrectly configured at deployment".

### Jxl version

`jxl`@`0.0.100`

**Note**: ref. [slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1583854424309500).

**Comment by jstrachan** [comment]
fixed - we can use the apps folder now for all apps
