### ISSUE TITLE
Support for kubectl > 1.17.0

### ISSUE THREAD

**Issue by bagnaram** [jenkins-x-labs/issues#12]
### Summary 
JXL fails fast if using a newer kubectl than 1.17.0.

### Steps to reproduce the behavior
`jxl boot start`
### Expected behavior
There should be an option to ignore this validation check.

### Actual behavior
`error: failed to verify requirements in dir /tmp/helmboot-543968906: package kubectl is using version 1.17.3 which is too new. The version stream requires a version earlier than 1.17.0`
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jxl                0.0.99
Kubernetes cluster v1.15.3
kubectl            v1.17.3
git                2.25.1
Operating System   "Arch Linux"


verifying packages
error: package kubectl is using version 1.17.3 which is too new. The version stream requires a version earlier than 1.17.0
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Cluster-API-AWS (CAPA)

### Operating system / Environment

Server: Centos 7
Client: Arch Linux

**Comment by bagnaram** [comment]
Workaround by modifying the upper limit of `jenkins-x-versions/packages/kubectl.yml` to 1.17.3

**Comment by jstrachan** [comment]
the upper bound is now 1.19.0
https://github.com/jenkins-x-labs/jenkins-x-versions/blob/master/packages/kubectl.yml#L2
