### ISSUE TITLE
labs getting started docs no quite working

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x-labs/issues#6]
Following the docs https://jenkins-x.io/docs/labs/boot/getting-started/

Created the cluster using the script from the installer repo, next ran
```
jxl boot create --git-public --env-git-public
```
But got this error:
```
cloning https://github.com/jenkins-x/jenkins-x-boot-helmfile-config.git to directory helmboot-108376129
saved file: helmboot-108376129/jx-requirements.yml
error: failed to verify requirements in dir helmboot-108376129: no $JX_SECRETS_YAML environment variable defined.
Please point this at your 'secrets.yaml' file.
See https://github.com/jenkins-x/enhancements/blob/master/proposals/2/docs/getting-started.md#setting-up-your-secrets
```
That link doesn't work but then I tried running the next step from the website which mentions secrets
```
jxl boot secrets edit --giturl https://github.com/myuser/environment-mycluster-dev.git
```
but I've not had the repo created from the previous step so no giturl to set AFAICT.

Also there's a few git repos checked out inside each other so I think the getting started flow could be tweaked a bit.

**Comment by jstrachan** [comment]
@rawlingsj think this one can be closed now
