### ISSUE TITLE
jxl: clone private repo using token from secrets

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x-labs/issues#9]
### Summary 

The user / token in the `secrets.yaml` for cloning private GitHub repositories aren't being used. Not possible to clone the private repository. 

### Steps to reproduce the behavior

Create a private repo under an GitHub organization account, authorize the users `jenkins-x-labs` token for the GitHub organization (#8) then attempt a `jx boot run --git-url https://github.com/ORG/REPO`

### Expected behavior

Private repo is cloned.

### Actual behavior

Cloning the private repo fails:
```
{"level":"info","msg":"Cloning https://github.com/ORG/REPO @ master to DIR\n","time":"2020-03-07T01:11:59Z"}
error: unable to clone https://github.com/ORG/REPO: failed to clone git URL https://github.com/ORG/REPO to directory: DIR: failed to fetch master from https://github.com/ORG/REPO in directory DIR: git output: fatal: could not read Username for 'https://github.com': No such device or address: failed to run 'git fetch origin master' command in directory 'DIR', output: 'fatal: could not read Username for 'https://github.com': No such device or address'
```

**Note**: [slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1583514424203300).

**Comment by masseybradley** [comment]
This works in latest version (`jxl`@`0.0.100`). If possible to hide the token in the logs output that would be great imho.

**Comment by jstrachan** [comment]
fixed
